import Image from 'next/image';
import React from 'react';

import { motion } from 'framer-motion';
import AboutMe from '../components/AboutMe';

export const metadata = {
  title: 'ercdwr | About Me',
  description: 'Generated by create next app',
};

const About = () => {
  return (
    <main className="flex h-[90vh] flex-col items-center justify-start mt-12 sm:px-12">
      <AboutMe />
    </main>
  );
};

export default About;
