import React from 'react';

export const metadata = {
  title: 'ercdwr | Projects',
  description: 'Generated by create next app',
};

const Projects = () => {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>MY PROJECTS</h1>
    </main>
  );
};

export default Projects;
